import Vue from 'vue'
import {
  QBtn, QIcon, QAlert, QTransition, QList, QSideLink, QItemSide, QItemMain, QListHeader, QInnerLoading,
  QLayout, QToolbar, QToolbarTitle, QAjaxBar, QCollapsible, QItem, QItemTile, QCard, QCardMain,
  QInfiniteScroll, QSpinner, QToggle, QInput, QCardTitle, QRating, QTooltip, QCardMedia, QItemSeparator,
  QSelect, QSlider, QRange, QAutocomplete, QSearch, QModal, QCardActions, QStepper, QStep, QGalleryCarousel,
  QRadio, QDataTable, QPagination, QFixedPosition, Events, QField,
  QCheckbox,
  QModalLayout,
  QStepperNavigation,
  QCardSeparator,
  QFabAction,
  QFab,
  QTabs,
  QProgress,
  QRouteTab,
  Toast,
  QScrollArea,
  QKnob,
  QDatetimeRange,
  QDatetime,
  QParallax
} from 'quasar'
const imports = {
  QProgress,
  QFixedPosition,
  QCheckbox,
  QModalLayout,
  QStepperNavigation,
  QFabAction,
  QFab,
  QAutocomplete,
  QTabs,
  QRouteTab,
  QScrollArea,
  QBtn,
  QIcon,
  QAlert,
  QTransition,
  QList,
  QSideLink,
  QItemSide,
  QItemMain,
  QListHeader,
  QInnerLoading,
  QLayout,
  QToolbar,
  QToolbarTitle,
  QAjaxBar,
  QCollapsible,
  QItem,
  QItemTile,
  QCard,
  QInfiniteScroll,
  QSpinner,
  QToggle,
  QInput,
  QRating,
  QTooltip,
  QItemSeparator,
  QSelect,
  QSlider,
  QRange,
  QSearch,
  QModal,
  QStepper,
  QStep,
  QGalleryCarousel,
  QRadio,
  QDataTable,
  QPagination,
  Events,
  QField,
  Toast,
  QCardTitle,
  QCardMedia,
  QCardActions,
  QCardSeparator,
  QCardMain,
  QKnob,
  QDatetimeRange,
  QDatetime,
  QParallax
}
Object.keys(imports).forEach(component => {
  Vue.component(component, imports[component])
})
